import Head from "next/head";
import Image from "next/image";
import FeaturedSection from "../components/featured/featured";
import HeroSection from "../components/hero-section/hero";
import SectionHow from "../components/how-section/how-section";
import MealSection from "../components/meal/meal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <FeaturedSection />
      <SectionHow />
      <MealSection />
    </>
  );
}
